# Generated by Django 3.1.4 on 2021-01-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default='Lorem ipsum dolor sit amet elit. Id quaerat amet ipsum sunt et quos dolorum.', max_length=1000),
            preserve_default=False,
        ),
    ]
