# Generated by Django 3.1.4 on 2021-01-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.URLField(max_length=256),
        ),
    ]
