# Generated by Django 3.1.4 on 2021-01-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=150)),
                ('phone_number', models.CharField(max_length=15)),
                ('message', models.TextField(max_length=1024)),
            ],
        ),
    ]
